version: 2.0

machine:
  ghc:
  version: 8.0.2

dependencies:
  - pre: haskell-stack

jobs:
  build:
    machine: true
    steps:
      - run: |
          echo Setting up...
          stack setup
          stack build --fast
