version: 2.0

machine:
  ghc:
  version: 8.0.2

jobs:
  build:
    machine: true
    steps:
      - run:
          name: Install stack
          command: curl -sSL https://get.haskellstack.org/ | sh
      - checkout
      - run:
          name: Setup stack
          command: stack setup
      - run:
          name: Build project
          command: stack build --fast --install-ghc
      - run:
          name: test
          command: stack test
