version: 2.0

machine:
  ghc:
  version: 8.0.2

jobs:
  build:
    machine: true
    steps:
      - run: |
          echo installing stack ...
          curl -sSL https://get.haskellstack.org/ | sh
      - checkout
      - run: ls -la
      - run: |
          echo Setting up...
          echo `pwd`
          cat stack.yml
          stack setup
      - run: |
          echo Building ...
          stack build --fast --install-ghc
